# Generated by Django 2.2.6 on 2019-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_list',
            name='LCD_SP',
            field=models.CharField(default='exit', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price_list',
            name='battery_replacement',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price_list',
            name='battery_type',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price_list',
            name='user_model_1',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price_list',
            name='user_model',
            field=models.CharField(choices=[('IPhone', 'IPhone'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('Meizu', 'Meizu'), ('Xiaomi', 'Xiaomi'), ('Nokia', 'Nokia'), ('Microsoft', 'Microsoft'), ('Prestigio', 'Prestigio'), ('Sony', 'Sony'), ('Alkatel', 'Alcatel'), ('Asus', 'Asus'), ('Aser', 'Aser'), ('Amigo', 'Amigo'), ('Amoi', 'Amoi'), ('BlackView', 'BlackView'), ('BLU', 'BLU'), ('BQ', 'BQ'), ('BlackBerry', 'BlackBerry'), ('CAT', 'CAT'), ('Caterpillar', 'Caterpillar'), ('Coolpad', 'Coolpad'), ('Cubot', 'Cubot'), ('Doogee', 'Doogee'), ('Doro', 'Doro'), ('Elephone', 'Elephone'), ('Estar', 'Estar'), ('Gigabyte', 'Gigabyte'), ('Getnord', 'Getnord'), ('Google', 'Google'), ('HTC', 'HTC'), ('HomTom', 'HomTom'), ('HP', 'HP'), ('Kazam', 'Kazam'), ('Lenovo', 'Lenovo'), ('LG', 'Lg'), ('MyPhone', 'MyPhone'), ('Nous', 'Nous'), ('OnePlus', 'OnePlus'), ('Oukitel', 'Oukitel'), ('Zopo', 'Zopo'), ('ZTE', 'ZTE'), ('------->', '------->')], max_length=20),
        ),
    ]
