# Generated by Django 2.2.6 on 2019-12-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191213_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_list',
            name='battery_replacement',
        ),
        migrations.RemoveField(
            model_name='price_list',
            name='battery_type',
        ),
        migrations.RemoveField(
            model_name='price_list',
            name='user_model_1',
        ),
    ]
