# Generated by Django 2.2.6 on 2019-12-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191213_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_list',
            name='battery_replacement',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
