# Generated by Django 2.2.6 on 2019-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_price_list_battery_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_list',
            name='battery_type',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price_list',
            name='user_model_1',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
