# Generated by Django 2.2.6 on 2019-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191213_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_list',
            name='battery_type',
            field=models.CharField(max_length=20),
        ),
    ]
