# Generated by Django 2.2.6 on 2019-12-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_price_list_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_list',
            name='owner',
        ),
    ]
