# Generated by Django 2.2.6 on 2019-12-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_price_list_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_model', models.CharField(choices=[('IPhone', 'IPhone'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('Meizu', 'Meizu'), ('Xiaomi', 'Xiaomi'), ('Nokia', 'Nokia'), ('Microsoft', 'Microsoft'), ('Prestigio', 'Prestigio'), ('Sony', 'Sony'), ('Alkatel', 'Alcatel'), ('Asus', 'Asus'), ('Aser', 'Aser'), ('Amigo', 'Amigo'), ('Amoi', 'Amoi'), ('BlackView', 'BlackView'), ('BLU', 'BLU'), ('BQ', 'BQ'), ('BlackBerry', 'BlackBerry'), ('CAT', 'CAT'), ('Caterpillar', 'Caterpillar'), ('Coolpad', 'Coolpad'), ('Cubot', 'Cubot'), ('Doogee', 'Doogee'), ('Doro', 'Doro'), ('Elephone', 'Elephone'), ('Estar', 'Estar'), ('Gigabyte', 'Gigabyte'), ('Getnord', 'Getnord'), ('Google', 'Google'), ('HTC', 'HTC'), ('HomTom', 'HomTom'), ('HP', 'HP'), ('Kazam', 'Kazam'), ('Lenovo', 'Lenovo'), ('LG', 'Lg'), ('MyPhone', 'MyPhone'), ('Nous', 'Nous'), ('OnePlus', 'OnePlus'), ('Oukitel', 'Oukitel'), ('Zopo', 'Zopo'), ('ZTE', 'ZTE'), ('------->', '------->')], max_length=20)),
                ('user_model_1', models.CharField(max_length=20)),
                ('user_detail', models.CharField(choices=[('Battery', 'Battery'), ('Back_cover', 'Back_cover'), ('Camera_back', 'Camera_back'), ('Camera_front', 'Camera_front'), ('Flex_charging', 'Flex_charging'), ('Flex_ON/OFF', 'Flex_ON/OFF'), ('Flex_camera', 'Flex_camera'), ('LCD_moduli', 'LCD_moduli'), ('LCD', 'LCD'), ('Touch', 'Touch')], max_length=20)),
                ('detail_quality', models.CharField(choices=[('SP', 'SP'), ('OR', 'OR'), ('HQ', 'HQ'), ('COPY', 'COPY')], max_length=10)),
                ('detail_comment', models.CharField(max_length=20)),
                ('detail_price', models.CharField(max_length=5)),
                ('detail_quantity', models.CharField(max_length=5)),
            ],
        ),
    ]
