# Generated by Django 2.2.6 on 2019-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_details_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='user_detail',
            field=models.CharField(choices=[('Battery', 'Battery'), ('Back_cover', 'Back_cover'), ('Camera_back', 'Camera_back'), ('Camera_front', 'Camera_front'), ('Flex_charging', 'Flex_charging'), ('Flex_ON/OFF', 'Flex_ON/OFF'), ('Flex_camera', 'Flex_camera'), ('LCD_module', 'LCD_module'), ('LCD', 'LCD'), ('Touch', 'Touch')], max_length=20),
        ),
    ]
