# Generated by Django 2.2.6 on 2020-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_handbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_list',
            name='LCD_HQ',
            field=models.CharField(default='*', max_length=6),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='LCD_SP',
            field=models.CharField(default='*', max_length=6),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='LCD_orig',
            field=models.CharField(default='*', max_length=6),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='battery_replacement',
            field=models.CharField(default='*', max_length=6),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='battery_type',
            field=models.CharField(default='*', max_length=20),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='charging',
            field=models.CharField(default='*', max_length=6),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='record_1',
            field=models.CharField(default='*', max_length=20),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='record_2',
            field=models.CharField(default='*', max_length=20),
        ),
        migrations.AlterField(
            model_name='price_list',
            name='record_3',
            field=models.CharField(default='*', max_length=20),
        ),
    ]
