# Generated by Django 2.2.6 on 2020-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200104_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='detail_comment',
            field=models.CharField(default='*', max_length=20),
        ),
    ]
