# Generated by Django 2.2.6 on 2020-01-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200104_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='designation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='handbook_model',
            field=models.CharField(max_length=30),
        ),
    ]
