# Generated by Django 2.2.6 on 2020-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200120_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='detail_visible',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
