# Generated by Django 2.2.6 on 2020-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200120_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='details_visible',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
