# Generated by Django 2.2.6 on 2020-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_send_finish',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='message_send_start',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
