# Generated by Django 2.2.6 on 2020-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0002_auto_20200120_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_send_start',
            field=models.CharField(default='9.00', max_length=5),
        ),
    ]
