# Generated by Django 2.2.6 on 2020-01-28 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_email', '0003_auto_20200128_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='free_set',
        ),
        migrations.RemoveField(
            model_name='post',
            name='message_send_finish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='message_send_start',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reg_num_set',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type_message',
        ),
        migrations.CreateModel(
            name='Settings_common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_reg_letter', models.CharField(default='NUM', max_length=5)),
                ('number_reg_start', models.CharField(max_length=5)),
                ('message_send_start', models.CharField(default='9.00', max_length=5)),
                ('message_send_finish', models.CharField(max_length=5)),
                ('details_visible', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('type_message', models.CharField(max_length=20)),
                ('reg_num_set', models.CharField(max_length=20)),
                ('free_set', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
