# Generated by Django 2.2.6 on 2020-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0004_auto_20200128_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_common',
            name='message_send_finish',
            field=models.CharField(default='17.00', max_length=5),
        ),
    ]
