# Generated by Django 2.2.6 on 2020-02-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0007_auto_20200131_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_common',
            name='number_reg_start',
            field=models.IntegerField(default=0),
        ),
    ]
