# Generated by Django 2.2.6 on 2020-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0008_auto_20200204_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_message_start', models.CharField(max_length=5)),
                ('send_message_finish', models.CharField(max_length=5)),
            ],
        ),
    ]
