# Generated by Django 2.2.6 on 2019-10-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
