# Generated by Django 2.2.6 on 2019-10-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobil_defect_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.TextField(max_length=50),
        ),
    ]
