# Generated by Django 2.2.6 on 2019-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20191030_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(choices=[('lcd', 'LCD'), ('not_charging', 'не заряжается'), ('wet', 'мокрый')], max_length=50),
        ),
    ]
