# Generated by Django 2.2.6 on 2019-11-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20191031_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(choices=[('lcd', 'LCD'), ('not_charging', 'не заряжается'), ('wet', 'мокрый')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(max_length=50),
        ),
    ]
