# Generated by Django 2.2.6 on 2019-11-01 13:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_auto_20191101_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lcd', 'LCD'), ('not_charging', 'не заряжается'), ('wet', 'мокрый')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('sam', 'Samsung'), ('son', 'Sony'), ('nok', 'Nokia')], max_length=50),
        ),
    ]
