# Generated by Django 2.2.6 on 2019-11-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_auto_20191101_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('sony', 'Sony'), ('nokia', 'Nokia')], max_length=50),
        ),
    ]
