# Generated by Django 2.2.6 on 2019-11-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_auto_20191107_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='date_end',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobil',
            name='date_take_away',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_1_tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('sony', 'Sony'), ('nokia', 'Nokia'), ('apple', 'Apple'), ('asus', 'Asus'), ('huawei', 'Huawei'), ('lenovo', 'Lenovo'), ('lg', 'Lg'), ('meizu', 'Meizu'), ('xiaomi', 'Xiaomi'), ('microsoft', 'Microsoft'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='price',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='status',
            field=models.CharField(choices=[('repair', 'ремонт'), ('rep_com', 'ремонт_завершён'), ('tel_take_away', 'забран')], max_length=20),
        ),
    ]
