# Generated by Django 2.2.6 on 2019-11-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0011_mobil_number_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='kod_tel',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
