# Generated by Django 2.2.6 on 2019-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0012_mobil_kod_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='date_end',
            field=models.CharField(default='***', max_length=12),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='date_take_away',
            field=models.CharField(default='***', max_length=12),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_reg',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='status',
            field=models.CharField(choices=[('repair', 'ремонт'), ('rep_com', 'ремонт_завершён'), ('tel_take_away', 'забран')], default='repair', max_length=20),
        ),
    ]
