# Generated by Django 2.2.6 on 2019-11-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0013_auto_20191111_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='imei',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_reg',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_sticker',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='price',
            field=models.IntegerField(max_length=4),
        ),
    ]
