# Generated by Django 2.2.6 on 2019-11-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0014_auto_20191116_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='imei',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_sticker',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='price',
            field=models.IntegerField(),
        ),
    ]
