# Generated by Django 2.2.6 on 2019-11-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0015_auto_20191116_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(choices=[('dnt_turn_on', 'не вкл'), ('lcd', 'LCD'), ('lcd/touch', 'LCD/Touch'), ('touch', 'Touch'), ('not_charging', 'не заряж'), ('wet', 'мокрый'), ('sim', 'sim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('sony', 'Sony'), ('nokia', 'Nokia'), ('apple', 'Apple'), ('asus', 'Asus'), ('huawei', 'Huawei'), ('lenovo', 'Lenovo'), ('lg', 'Lg'), ('meizu', 'Meizu'), ('xiaomi', 'Xiaomi'), ('microsoft', 'Microsoft'), ('redmi', 'Redmi'), ('------->', '------->')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_tel',
            field=models.CharField(default='+370', max_length=20),
        ),
    ]
