# Generated by Django 2.2.6 on 2019-11-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0016_auto_20191117_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='defect_1_tel',
            field=models.CharField(choices=[('dnt_turn_on', 'не вкл'), ('lcd', 'LCD'), ('lcd/touch', 'LCD/Touch'), ('touch', 'Touch'), ('not_charging', 'не заряж'), ('wet', 'мокрый'), ('sim', 'sim')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('meizu', 'Meizu'), ('xiaomi', 'Xiaomi'), ('nokia', 'Nokia'), ('microsoft', 'Microsoft'), ('sony', 'Sony'), ('alkatel', 'Alcatel'), ('asus', 'Asus'), ('blackberry', 'BlackBerry'), ('coolpad', 'Coolpad'), ('cubot', 'Cubot'), ('doogee', 'Doogee'), ('doro', 'Doro'), ('estar', 'Estar'), ('getnord', 'Getnord'), ('google', 'Google'), ('htc', 'HTC'), ('lenovo', 'Lenovo'), ('lg', 'Lg'), ('myphone', 'MyPhone'), ('zte', 'ZTE'), ('------->', '------->')], max_length=20),
        ),
    ]
