# Generated by Django 2.2.6 on 2019-11-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0017_auto_20191117_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='comment',
            field=models.CharField(default='***', max_length=200),
        ),
    ]
