# Generated by Django 2.2.6 on 2019-11-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0018_mobil_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='defect',
            field=models.CharField(default='***', max_length=30),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_1_tel',
            field=models.CharField(choices=[('nope', 'нет дефекта'), ('programm', 'programm'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('dnt_turn_on', 'не вкл'), ('not_charging', 'не заряж'), ('speaker', 'speaker'), ('buzzer', 'buzzer'), ('microphone', 'microphone'), ('hands_free', 'hands_free'), ('wi_fi', 'wi_fi'), ('wet', 'мокрый'), ('sim', 'sim')], default='***', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(choices=[('nope', 'нет дефекта'), ('programm', 'programm'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('dnt_turn_on', 'не вкл'), ('not_charging', 'не заряж'), ('speaker', 'speaker'), ('buzzer', 'buzzer'), ('microphone', 'microphone'), ('hands_free', 'hands_free'), ('wi_fi', 'wi_fi'), ('wet', 'мокрый'), ('sim', 'sim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('meizu', 'Meizu'), ('xiaomi', 'Xiaomi'), ('nokia', 'Nokia'), ('microphone', 'Microsoft'), ('sony', 'Sony'), ('alkatel', 'Alcatel'), ('asus', 'Asus'), ('blackberry', 'BlackBerry'), ('coolpad', 'Coolpad'), ('cubot', 'Cubot'), ('doogee', 'Doogee'), ('doro', 'Doro'), ('estar', 'Estar'), ('getnord', 'Getnord'), ('google', 'Google'), ('htc', 'HTC'), ('lenovo', 'Lenovo'), ('lg', 'Lg'), ('myphone', 'MyPhone'), ('zte', 'ZTE'), ('------->', '------->')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_tel',
            field=models.CharField(max_length=20),
        ),
    ]
