# Generated by Django 2.2.6 on 2019-11-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0019_auto_20191118_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='defect_1_tel',
            field=models.CharField(choices=[('nope', 'нет дефекта'), ('programm', 'programm'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('dnt_turn_on', 'не вкл'), ('not_charging', 'не заряж'), ('speaker', 'speaker'), ('buzzer', 'buzzer'), ('microsoft', 'microphone'), ('hands_free', 'hands_free'), ('wi_fi', 'wi_fi'), ('wet', 'мокрый'), ('sim', 'sim'), ('------->', '------->')], default='***', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(choices=[('nope', 'нет дефекта'), ('programm', 'programm'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('dnt_turn_on', 'не вкл'), ('not_charging', 'не заряж'), ('speaker', 'speaker'), ('buzzer', 'buzzer'), ('microsoft', 'microphone'), ('hands_free', 'hands_free'), ('wi_fi', 'wi_fi'), ('wet', 'мокрый'), ('sim', 'sim'), ('------->', '------->')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='state',
            field=models.CharField(choices=[('no visible defects', 'нет видимых дефектов'), ('damaded_LCD/Touch', 'повреждён экран/тоучскрин'), ('damaded_case', 'повреждён корпус'), ('damaded_back_cover', 'повреждена задняя крышка')], max_length=20),
        ),
    ]
