# Generated by Django 2.2.6 on 2019-11-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0022_mobil_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='imei',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='number_sticker',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='price',
            field=models.CharField(max_length=5),
        ),
    ]
