# Generated by Django 2.2.6 on 2019-11-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0023_auto_20191123_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='defect',
            field=models.CharField(default='...', max_length=30),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_1_tel',
            field=models.CharField(choices=[('programm', 'Programm'), ('kod', 'Код'), ('akkaunt', 'Аккаунт'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('dnt_1', 'Не вкл'), ('dnt_2', 'Не вкл, Мокрый'), ('dnt_3', 'Не вкл, Падал'), ('not_charging', 'Не заряж'), ('speaker', 'Speaker'), ('buzzer', 'Buzzer'), ('microphone', 'Microphone'), ('hands_free', 'Hands_Free'), ('wi_fi', 'Wi-Fi'), ('wet', 'Мокрый'), ('sim', 'Sim'), ('------->', '------->')], default='***', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(choices=[('programm', 'Programm'), ('kod', 'Код'), ('akkaunt', 'Аккаунт'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('dnt_1', 'Не вкл'), ('dnt_2', 'Не вкл, Мокрый'), ('dnt_3', 'Не вкл, Падал'), ('not_charging', 'Не заряж'), ('speaker', 'Speaker'), ('buzzer', 'Buzzer'), ('microphone', 'Microphone'), ('hands_free', 'Hands_Free'), ('wi_fi', 'Wi-Fi'), ('wet', 'Мокрый'), ('sim', 'Sim'), ('------->', '------->')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('meizu', 'Meizu'), ('xiaomi', 'Xiaomi'), ('nokia', 'Nokia'), ('microsoft', 'Microsoft'), ('sony', 'Sony'), ('alkatel', 'Alcatel'), ('asus', 'Asus'), ('blackberry', 'BlackBerry'), ('coolpad', 'Coolpad'), ('cubot', 'Cubot'), ('doogee', 'Doogee'), ('doro', 'Doro'), ('estar', 'Estar'), ('getnord', 'Getnord'), ('google', 'Google'), ('htc', 'HTC'), ('lenovo', 'Lenovo'), ('lg', 'Lg'), ('myphone', 'MyPhone'), ('nous', 'Nous'), ('zte', 'ZTE'), ('------->', '------->')], max_length=20),
        ),
    ]
