# Generated by Django 2.2.6 on 2019-11-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0024_auto_20191123_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='comment',
            field=models.CharField(default='*', max_length=200),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='date_end',
            field=models.CharField(default='*', max_length=12),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='date_take_away',
            field=models.CharField(default='*', max_length=12),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect',
            field=models.CharField(default='*', max_length=30),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_1_tel',
            field=models.CharField(choices=[('programm', 'Programm'), ('kod', 'Код'), ('akkaunt', 'Аккаунт'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('dnt_1', 'Не вкл'), ('dnt_2', 'Не вкл, Мокрый'), ('dnt_3', 'Не вкл, Падал'), ('not_charging', 'Не заряж'), ('speaker', 'Speaker'), ('buzzer', 'Buzzer'), ('microphone', 'Microphone'), ('hands_free', 'Hands_Free'), ('wi_fi', 'Wi-Fi'), ('wet', 'Мокрый'), ('sim', 'Sim'), ('------->', '------->')], default='*', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='kod_tel',
            field=models.CharField(default='*', max_length=20),
        ),
    ]
