# Generated by Django 2.2.6 on 2019-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0025_auto_20191124_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('iphone', 'IPhone'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('meizu', 'Meizu'), ('xiaomi', 'Xiaomi'), ('nokia', 'Nokia'), ('microsoft', 'Microsoft'), ('sony', 'Sony'), ('alkatel', 'Alcatel'), ('asus', 'Asus'), ('blackberry', 'BlackBerry'), ('coolpad', 'Coolpad'), ('cubot', 'Cubot'), ('doogee', 'Doogee'), ('doro', 'Doro'), ('estar', 'Estar'), ('getnord', 'Getnord'), ('google', 'Google'), ('htc', 'HTC'), ('lenovo', 'Lenovo'), ('lg', 'Lg'), ('myphone', 'MyPhone'), ('nous', 'Nous'), ('zte', 'ZTE'), ('------->', '------->')], max_length=20),
        ),
    ]
