# Generated by Django 2.2.6 on 2019-11-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0026_auto_20191124_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='model_tel',
            field=models.CharField(choices=[('IPhone', 'IPhone'), ('Samsung', 'Samsung'), ('Huawei', 'Huawei'), ('Meizu', 'Meizu'), ('Xiaomi', 'Xiaomi'), ('Nokia', 'Nokia'), ('Microsoft', 'Microsoft'), ('Sony', 'Sony'), ('Alkatel', 'Alcatel'), ('Asus', 'Asus'), ('BlackBerry', 'BlackBerry'), ('Coolpad', 'Coolpad'), ('Cubot', 'Cubot'), ('Doogee', 'Doogee'), ('Doro', 'Doro'), ('Estar', 'Estar'), ('Getnord', 'Getnord'), ('Google', 'Google'), ('HTC', 'HTC'), ('Lenovo', 'Lenovo'), ('LG', 'Lg'), ('MyPhone', 'MyPhone'), ('Nous', 'Nous'), ('ZTE', 'ZTE'), ('------->', '------->')], max_length=20),
        ),
    ]
