# Generated by Django 2.2.6 on 2019-11-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0028_auto_20191124_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='status',
            field=models.CharField(choices=[('ремонт', 'ремонт'), ('рем.завершен', 'ремонт_завершён'), ('забран', 'забран')], default='ремонт', max_length=20),
        ),
    ]
