# Generated by Django 2.2.6 on 2020-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0031_auto_20191130_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='email_client',
            field=models.EmailField(default='*', max_length=254),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_1_tel',
            field=models.CharField(choices=[('programm', 'Programm'), ('languige', 'Язык'), ('unlock', 'Отвязка'), ('kod', 'Код'), ('akkaunt', 'Аккаунт'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('не вкл', 'Не вкл'), ('не вкл, мокрый', 'Не вкл, Мокрый'), ('не вкл,падал', 'Не вкл, Падал'), ('not_charging', 'Не заряж'), ('speaker', 'Динамик'), ('buzzer', 'Зуммер'), ('microphone', 'Микрофон'), ('hands_free', 'Hands_Free'), ('wi_fi', 'Wi-Fi'), ('wet', 'Мокрый'), ('sim', 'Sim'), ('flex', 'Шлейф'), ('case', 'Корпус'), ('------->', '------->')], default='*', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='defect_tel',
            field=models.CharField(choices=[('programm', 'Programm'), ('languige', 'Язык'), ('unlock', 'Отвязка'), ('kod', 'Код'), ('akkaunt', 'Аккаунт'), ('lcd/touch', 'LCD/Touch'), ('lcd', 'LCD'), ('touch', 'Touch'), ('не вкл', 'Не вкл'), ('не вкл, мокрый', 'Не вкл, Мокрый'), ('не вкл,падал', 'Не вкл, Падал'), ('not_charging', 'Не заряж'), ('speaker', 'Динамик'), ('buzzer', 'Зуммер'), ('microphone', 'Микрофон'), ('hands_free', 'Hands_Free'), ('wi_fi', 'Wi-Fi'), ('wet', 'Мокрый'), ('sim', 'Sim'), ('flex', 'Шлейф'), ('case', 'Корпус'), ('------->', '------->')], max_length=20),
        ),
    ]
