# Generated by Django 2.2.6 on 2020-01-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0032_auto_20200111_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='email_client',
            field=models.EmailField(default='*@gmail.com', max_length=254),
        ),
    ]
