# Generated by Django 2.2.6 on 2020-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0033_auto_20200114_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='number_tel',
            field=models.CharField(default='+370', max_length=20),
        ),
    ]
