# Generated by Django 2.2.6 on 2020-01-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0034_auto_20200115_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='number_reg_letter',
            field=models.CharField(default='NUM', max_length=5),
        ),
        migrations.AddField(
            model_name='mobil',
            name='number_reg_start',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
