# Generated by Django 2.2.6 on 2020-01-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0035_auto_20200120_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobil',
            name='number_reg_letter',
        ),
        migrations.RemoveField(
            model_name='mobil',
            name='number_reg_start',
        ),
    ]
