# Generated by Django 2.2.6 on 2020-02-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0036_auto_20200128_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='number_reg',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
