# Generated by Django 2.2.6 on 2020-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0037_auto_20200204_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobil',
            name='number_reg',
            field=models.IntegerField(default=0),
        ),
    ]
